#!/usr/bin/env bash
# Script to display information about subdomain

# Bash function to display information about a specific subdomain
#display_info() {
 # local domain=$1
  #local subdomain=$2

  # Use dig command to retrieve DNS information for the subdomain
  #local record_type=$(dig +short $subdomain.$domain | awk '{print $4}')
  #local destination=$(dig +short $subdomain.$domain | awk '{print $5}')

  #echo "The subdomain $subdomain is a $record_type record and points to $destination"
#}

# Extract domain and subdomain parameters from command line arguments
#domain=$1
#subdomain=$2

# Check if subdomain parameter is provided
#if [ -z "$subdomain" ]; then
  # Display information for subdomains www, lb-01, web-01, and web-02
  #display_info $domain "www"
  #display_info $domain "lb-01"
  #display_info $domain "web-01"
 # display_info $domain "web-02"
#else
  # Display information for the specified subdomain
 # display_info $domain $subdomain
#fi

dns_config () {
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  dns_config "$1" "www"
  dns_config "$1" "lb-01"
  dns_config "$1" "web-01"
  dns_config "$1" "web-02"
elif [ "$#" == 2 ]
then
  dns_config "$1" "$2"
fi
